---
title: ""
---

#map

```{r}
library(scales)
library(ggspatial) 
library(gsheet)
library(ggrepel)
library(cowplot)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
library(tidyverse)
map = gsheet2tbl("https://docs.google.com/spreadsheets/d/1JAEAXsmb928CsyCzRbfTP2ilruEof2Qkr_zWUfaknOc/edit?gid=1402084465#gid=1402084465")

BRA = ne_states(
  country = "Brazil",
  returnclass = "sf"
)
library(geobr)
municipios <- read_municipality(code_muni = "all", year = 2020)
municipios = municipios %>% filter(name_state ==  c("Paraná","São Paulo", "Mato Grosso do Sul","Goiás","Minas Gerais","Distrito Federal"))

states <- filter(BRA, 
                 name_pt == "Paraná"|
                 name_pt == "São Paulo"|
                 name_pt == "Mato Grosso do Sul"|
                 name_pt == "Goiás"|
                 name_pt == "Minas Gerais"|
                 name_pt == "Federal")
unique(BRA$name_pt)
states = states %>% 
  mutate(id = case_when(
    name_pt == "Paraná" ~ "PR",
    name_pt == "São Paulo" ~ "SP",
    name_pt == "Mato Grosso do Sul" ~ "MS",
    name_pt == "Goiás" ~ "GO",
    name_pt == "Minas Gerais" ~ "MG",
    name_pt == "Federal" ~ "DF"))

SUL = ne_states(
  country = c("Argentina", "Uruguay", "Paraguay", "Colombia", "Bolivia"),
  returnclass = "sf")

br_sf <- ne_states(geounit = "brazil",
                   returnclass = "sf")





```

```{r}



library(ggplot2)
library(cowplot)  

map3 = map |>  filter(estado != "PR")
mapa_principal <- ggplot() +
  #geom_sf(data = SUL, fill = "white", color = "white") +
  geom_sf(data = BRA, fill = "white", color = "gray60", size = 0.2)  + 
  geom_sf(data = subset(BRA, postal %in% c("GO", "MG", "PR", "MS", "SP", "DF")), 
        fill = NA, color = "black", size = 1) + 
  geom_text(data = states, aes(x = longitude, y = latitude, label = id), 
            size = 3, hjust = 0.8, color = "black", fontface = "bold") +
  geom_point(data = map, aes(x = lon, y = lat, size = n, color = sev), 
             alpha = 0.8) +
  scale_color_gradientn(colors = c("#313695", "#74add1", "#ffcc00", "#fd8d3c", "#e31a1c", "#800026"),
                      breaks = seq(0, 70, by = 15), 
                      limits = c(0, 70)) +
  scale_size_continuous(range = c(1, 5), breaks = c(1, 5, 12)) +
  theme_minimal_grid() +
  coord_sf(xlim = c(-60, -37), ylim = c(-27, -12), expand = FALSE) +
   guides(size = FALSE,  
         color = guide_colorbar(title = "Severity (%)", 
                                direction = "horizontal",
                                title.position = "top"))  +
    theme(legend.position = c(0.9, 0.01),  
        legend.justification = c(1, 0),
         legend.direction = "horizontal",
         legend.title.align = 0.5,
         panel.border = element_rect(color = "black", fill = NA, size = 1))+
   annotation_north_arrow(location = "br", which_north = "true", 
                         pad_x = unit(5.86, "in"), pad_y = unit(0.3, "in"), 
                         style = north_arrow_fancy_orienteering, 
                         height = unit(1.2, "cm"), width = unit(1.1, "cm")) +
   annotation_scale(location = "br", 
                   width_hint = 0.1, 
                   height = unit(0.2, "cm"), 
                   text_cex = 0.6, 
                   pad_x = unit(5.8, "in"), 
                   pad_y = unit(0.2, "in")) +
  labs(x = "Longitude", y = "Latitude")
mapa_principal



pr_municipios <- read_municipality(code_muni = "all", year = 2020) %>%
  filter(name_state == "Paraná")

BRA <- ne_states(country = "Brazil", returnclass = "sf")
pr_estado <- BRA %>% filter(name_pt == "Paraná")
map2 = map |> filter(estado == "PR")

mapa_brasil <- ggplot() +
  geom_sf(data = BRA, fill = "white", color = "black", size = 0.2) +  
  geom_sf(data = subset(BRA, postal %in% c("GO", "MG", "PR", "MS", "SP")), 
          fill = "gray40", color = "black", size = 0.6) +  
  theme_map() +
    theme(
    panel.background = element_rect(fill = "white", color = NA),  
    plot.background = element_rect(fill = "white", color = NA),   
    panel.border = element_rect(color = "black", fill = NA, size = 1)) 
```

```{r}
library(patchwork)

mapa_principal + 
  inset_element(mapa_brasil, 
                left = 0.8, bottom = 0.7,  
                right = 0.99, top = 1) 
#ggsave("map.png", height=8, width=8, dpi = 600, bg = "white")


```
