---
title: ""
---
#sev x Yield 

#Packages
```{r}
library(gsheet)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(scales)
```


```{r}
gain = gsheet2tbl("https://docs.google.com/spreadsheets/d/1OFccjyBsxeVPchSNfFy7hvMp23PCoZ4bt2YpInABiKg/edit?usp=sharing") 


gain = gain |>  mutate(fungicide = recode(fungicide, 
                          'trat_A20259' = "DIF + PYDI",
                          "ABACUS HC (Controle Positivo)"= "PYRA + EPOX",
                          "BAS 753 02 F" = "PYRA + FLUX + MEFE",
                          "FOX XPRO" = "TRFX + PROT + BIX",
                          "OSKESTRA SC" = "PYRA + FLUX",
                          "PREVINIL" = "CLOR",
                          "TRIDIUM" = "AZO + TEBU + MANC",
                           "UNIZEB GOLD (Controle Positivo, multissítio)" = "MANC"
                          )) 
gain %>% 
  mutate(fungicide = factor(fungicide, 
                           levels = c("MANC", "CLOR", 
                                      "DIF + PYDI", "PYRA + EPOX", "PYRA + FLUX + MEFE", 
                                      "TRFX + PROT + BIX", "PYRA + FLUX", 
                                      "AZO + TEBU + MANC"))) |> 
  ggplot(aes(mean, mean_yld)) + 
  geom_errorbar(aes(ymin = ci.lb_yld, ymax = ci.ub_yld, color = fungicide), alpha = 0.8, width=0, size= 0.8)+
  geom_errorbarh(aes(xmin = low, xmax = up, color = fungicide), alpha = 0.8, height= 0, size= 0.8)+
  geom_point(aes(mean, mean_yld, color = fungicide), size = 3)+
  #scale_y_continuous(breaks=seq(0, 2500, 500), limits=c(0,2500))+
  #scale_x_continuous(breaks=seq(0, 80, 10), limits=c(0, 80))+
  #theme_minimal_grid()+
  scale_color_colorblind()+
  labs(y = "Yield return (kg/ha)", x = "Efficacy (%)", color = "Foliar fungicide")+
  theme(axis.text=element_text(size=12), 
        axis.title=element_text(size=12, face = "bold"),
        legend.position = "right",
        legend.title.align = 0.5,
        strip.text.x = element_text(size = 14, face = "bold"),
        legend.title = element_text(size=12, face = "bold"))

#ggsave("yld_eff.png", height=5, width=10, dpi = 600, bg = "white")

```